### PR TITLE
Wrap @import statements into precompiler condition

### PR DESCRIPTION
**Pull request by ggiraudon**
Wrap @import statements into precompiler condition to avoid build problems when modules are disabled.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This breaks CI :/

**Comment by ggiraudon** [comment]
Hi Micheal,

I'm not sure the patch itself breaks CI.
The CI log hints at a git issue more than anything else.
The error seems to be :

The command "git -C /usr/local/Library/Taps/homebrew/homebrew-core checkout 14aa94dd Formula/erlang.rb" failed and exited with 128 during .

which looks like something triggered by the test script itself.

Any chance you can take a look ?

**Comment by michaelklishin** [comment]
I restarted the build, lets see if the failure was transient.

**Comment by michaelklishin** [comment]
Right, so something is not right in the Travis environment :(

**Comment by camelpunch** [comment]
We were using a now-broken method of pinning a version of package in Homebrew, as 3.6.3 got packaged into Homebrew even though it didn't work with Erlang 19. I've removed that broken pinning technique as 3.6.4 is now available.

If that works on master, please rebase or merge to trigger CI with that change.

**Comment by camelpunch** [comment]
@ggiraudon Master is now green after that change - please rebase.

**Comment by ggiraudon** [comment]
Sorry... feel a bit lost here... did you mean you want me to rebase to master and then reapply my patch ?
I dont think my 2 trivial contributions have any impact on CI. 
This pull request should still merge fine against the current master, shouldnt it ?
Let me know if there's anything you'd like me to do.

**Comment by michaelklishin** [comment]
@ggiraudon rebase your branch and push it. That will update this PR.

**Comment by michaelklishin** [comment]
Merged master in and re-submitted as #96.

**Comment by michaelklishin** [comment]
#96 is in. Thank you, @ggiraudon!

**Pull request closed without merging**
