### PR TITLE
Ability to define publish options and properties

### PR DESCRIPTION
**Pull request by hasbean**
I needed a way to send userId, replyTo, correlationId in the headers, but I couldn't find a way to do it.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you. This needs some tests. Feel free to borrow [this Bunny spec example](https://github.com/ruby-amqp/bunny/blob/master/spec/higher_level_api/integration/message_properties_access_spec.rb) for inspiration.

**Comment by camelpunch** [comment]
In addition to tests (see [RMQAllocatedChannelTest](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClientTests/RMQAllocatedChannelTest.swift)), we would want changes to the publish interfaces in [RMQQueue](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClient/RMQQueue.m) and [RMQExchange](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClient/RMQExchange.m) with associated tests ([RMQExchangeTest](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClientTests/RMQExchangeTest.swift) and [RMQQueueTest](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClientTests/RMQQueueTest.swift). Both of these delegate to [RMQAllocatedChannel](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClient/RMQAllocatedChannel.m).

Fixing this has been scheduled internally, so if we get to it before you do, we'll re-implement. We'll let you know when we're starting work. Thanks!

**Comment by hasbean** [comment]
Sadly I barely have enough time to work on this :(  I just thought I'd help out anyone who's in the same boat as me.  If I can finish my project on time, I'll work on this pull request.

By the way, this library is a life-saver.  There's barely any of them out there for ObjC/Swift that work.

**Comment by michaelklishin** [comment]
@hasbean no worries, we can finish it ourselves. Thank you for your feedback.

**Comment by camelpunch** [comment]
@hasbean @sasikiran Starting work on a TDD'd implementation now.

**Comment by camelpunch** [comment]
Closing in favour of #65 as a feature request.

**Pull request closed without merging**
