### PR TITLE
Change deployment target to 10.9

### PR DESCRIPTION
**Pull request by afedor**
It would be super helpful to change the deployment target to 10.9 instead of 10.11 so this can be used more widely in other projects. It isn't likely that a lot of people use 10.9, but there don't seem to be any reasons not to support it

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thanks. We can do this. I hope to port this client entirely to Swift in the future but growing convinced it should be a separate project, so that this client lives on in bug fix only mode.

**Comment by afedor** [comment]
Sounds good to me

**Comment by michaelklishin** [comment]
I don't know what's going on with Travis' PR test, will test locally later today.

**Comment by michaelklishin** [comment]
Unfortunately this would require giving up some Swift features:

```
▸ Compiling ConnectionHelper.swift

Testing failed:
	'global(qos:)' is only available on OS X 10.10 or newer
	'utility' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'userInteractive' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'background' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'utility' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'userInteractive' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'background' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'default' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'userInteractive' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'default' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'background' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'userInteractive' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'utility' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'background' is only available on OS X 10.10 or newer
	'global(qos:)' is only available on OS X 10.10 or newer
	'userInteractive' is only available on OS X 10.10 or newer
** TEST FAILED **
```

@afedor I assume it is easy enough to override this target. If not, I'm all for introducing a way to override it on a per-environment basis.

**Comment by afedor** [comment]
I'm using Carthage, which doesn't have a way to change options, but it is easy enough to change it by hand.

**Pull request closed without merging**
