### PR TITLE
Add arguments to a consumer

### LINKED ISSUE #106: RMQBasicConsume can't add arguments to a consumer
It seems it's not possible to set the arguments to the RMQBasicConsume.

In the RMQMethods+Convenience.m 
the implementation RMQBasicConsume initWithQueue sets the arguments with a new empty RMQTable 

[https://github.com/rabbitmq/rabbitmq-objc-client/blob/121a96b20618f58c431eb898ed983d283b9f046b/RMQClient/RMQMethods%2BConvenience.m](url)

### PR DESCRIPTION
**Pull request by timhonders**
Fixes #106.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Instructions on running tests can be [found in README](https://github.com/rabbitmq/rabbitmq-objc-client#running-tests). `.travis.yml` might provide extra clues. Running a RabbitMQ 3.6.6 node locally (see what kind of configuration is needed above) is a requirement.

**Comment by timhonders** [comment]
I will check it out.

**Comment by michaelklishin** [comment]
I addressed the issue above in #108.

**Comment by timhonders** [comment]
Nice tnx

**Pull request closed without merging**
