### PR TITLE
Avoid memory leaks in RMQConnection dependency graph (take 4)

### PR DESCRIPTION
**Pull request by BarryDuggan**
## Proposed Changes

This PR is a work in progress.
It is an attempt to solve memory leaks in this client.
These memory leaks can occur when we close a connection, make it nil, and then attempt to create a new connection.
In this case we would expect to have 1 connection, but in fact we have 2.
See [this discussion](https://github.com/rabbitmq/rabbitmq-objc-client/discussions/194) for more details.

## Change Made 

- Added a new Memory Test Target to make it easier the run memory graph against changes made.
- Broke several retain cycles by using weak references.
- Close channels and nil references when closing connections

This PR is verified by all unit tests passing.

That said it will need as many eyes on it as possible because so many areas of the code base have been touched.

### CODE REVIEW

**Comment by BarryDuggan** [comment]
@michaelklishin I've updated the branch to close channels when closing a connection. 
There's now now memory leaks and the tests are passing.

I'm cautiously optimistic that we're headed in the right direction.....

**Comment by michaelklishin** [comment]
OK. Closing all channels is not necessary when a connection is closed, as they won't be useable any more. We can "close" (release) them without going through the `channel.close` — `channel.close-ok` network roundtrip but some clients do that
and it's OK since most connections don't have a lot of channels open on them.

**Comment by michaelklishin** [comment]
@BarryDuggan all tests pass 10 runs in a row 👍 We need to add the new memory leak tests to the list of targets executed with `gmake` and `gmake tests_{ios,osx}`, otherwise I have no objections to merging this.

**Comment by michaelklishin** [comment]
Looks like `MemoryTestTests` and friends are just stubs produced by XCode? Do we care to implement them (this kind of tests can be tricky to get right) or should they be removed?

**Comment by BarryDuggan** [comment]
> Looks like `MemoryTestTests` and friends are just stubs produced by XCode? Do we care to implement them (this kind of tests can be tricky to get right) or should they be removed?

We can delete them.
I'll just add a simple check for nil test in the existing test suite instead.

**Comment by michaelklishin** [comment]
Perfect. Let's do that and merge then :) Thank you!

**Review by michaelklishin — APPROVED** [review]

**Comment by BarryDuggan** [comment]
@michaelklishin will we be bumping the cocoapods versions / making a release for these changes?

**Comment by michaelklishin** [comment]
Yes, some time later this week. I haven't done a release in a good year so need to re-learn how that's done.

**Comment by michaelklishin** [comment]
It took me a while but [`0.12.0`](https://github.com/rabbitmq/rabbitmq-objc-client/releases/tag/v0.12.0) has been [published to CocoaPods Trunk](https://cocoapods.org/pods/RMQClient).

@BarryDuggan let me know if I've missed anything.

**Comment by axel012** [comment]
> It took me a while but [`0.12.0`](https://github.com/rabbitmq/rabbitmq-objc-client/releases/tag/v0.12.0) has been [published to CocoaPods Trunk](https://cocoapods.org/pods/RMQClient).
> 
> @BarryDuggan let me know if I've missed anything.

Found bug with last change, using weak for heartBeatSender is causing to be dealocated before calling start causing disconnects issues since the heartbeat is nil.

Steps to reproduce: 
- Start a new connection calling any init function

In the image below we watch _heartBeatSender variable for changes between the init flow, the value is set but then its nil again when the instance is created.
image

**Comment by michaelklishin** [comment]
@axel012 please submit a PR. Thank you.

**Pull request merged**
